stages:
  retrieve_html:
    cmd: python src/stage_01_retrieve_html.py --config config/config.yaml
    deps:
      - src/stage_01_retrieve_html.py
      - src/utils/all_utils.py
      - config/config.yaml
      
    outs:
      - artifacts/raw_data/Html_Data/

  Extracting and combining data:
    cmd: python src/stage_02_Extract_combine.py --config config/config.yaml
    deps:
      - src/stage_02_Extract_combine.py
      - src/utils/all_utils.py
      - config/config.yaml
      #- artifacts/data/AQI/aqi2013.csv
      - artifacts/raw_data/AQI/
      - artifacts/raw_data/Html_Data
    outs:
      - artifacts/raw_data/Real-Data/

  